modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="karmamod"
version="1.0.0"
displayName="Karma Mod"
authors="Sen"
description="Karma Modu"

[[dependencies.karmamod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.karmamod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
    
