modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "karmamod"
version = "1.0.0"
displayName = "Karma Mod"
credits = "İnsanazor"
authors = "İnsanazor"
description = '''
Kurbağalardan Warden'a kadar tüm dönüşüm mekaniklerini ve kurallarını içeren mod.
'''

[[dependencies]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"
